### ISSUE TITLE
Mesa version too old, does not recognize vega gpus.

### ISSUE THREAD

**Issue by GloriousEggroll** [flatpak/freedesktop-sdk-images#71] opened 2017-12-15 16:19 UTC
Hi, I am not sure if this is the correct place to post this, so I do apologize in advance if not. I was in the middle of creating a flatpak of league of legends - which is working, however the version of mesa is too old and my gpu (Vega 64) is unrecognized, so the game falls back to software rendering:

libGL error: pci id for fd 75: 1002:687f, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: pci id for fd 75: 1002:687f, driver (null)
pci id for fd 76: 1002:687f, driver (null)
libGL error: failed to create dri screen

the runtimes/sdk I used were as follows:
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user install flathub org.freedesktop.Platform/i386/1.6

according to the runtime details (https://flatpak.org/runtimes), the runtime used for freedesktop (1.6) includes:
mesa 17.0.5
however initial vega support did not land until 17.1, and bugs were ironed out in 17.2. I see a patch in this repo that updates mesa to 17.2.2, but I don't believe this is included in 1.6? If not, is there any way to pull a git version of the sdk to install?

some insight on this would be appreciated, thanks!

**Comment by alexlarsson** [comment] 2017-12-15 16:23
You should be able to install org.freedesktop.Platform.GL.default//1.6 from flathub and get a newer mesa (17.2.2 atm)

**Comment by GloriousEggroll** [comment] 2017-12-15 21:19
This did resolve the issue with my card not being recognized, however I'm only getting around 30 fps as opposed to much larger numbers natively on a vega 64, are there any other packages I should pull? Thanks for your response

**Comment by TingPing** [comment] 2017-12-15 22:41
@GloriousEggroll What is the Mesa version on your host?

**Comment by GloriousEggroll** [comment] 2017-12-16 00:51
My host runs mesa-git, but also works fine on 17.2.6 (latest official from arch)

**Comment by GloriousEggroll** [comment] 2017-12-16 04:39
I can verify however that my second machine with an nvidia 1050 runs the game appropriately without issues. This should confirm that the issue comes down to being a problem with mesa drivers. I do not have a non-vega amd card to test with. Will reach out to some friends to see if I can get some extra input

**Comment by GloriousEggroll** [comment] 2017-12-17 01:33
have a friend with an rx 480 who had the same issue I did, we both only got about 30 fps using flatpak's mesa 17.2.2

**Comment by alexlarsson** [comment] 2017-12-17 17:26
We could try just updating to 17.2.6 and see if that makes a difference

**Comment by GloriousEggroll** [comment] 2017-12-17 18:36
It's worth noting 17.3 released this week and includes vaapi h.264 encoding support (for things such as using ffmpeg to record h.264 using the gpu). 17.2.6 doesnt include this, but either one should work none the less

**Comment by TingPing** [comment] 2017-12-17 22:18
OBS was on my todo list.

**Comment by alexlarsson** [comment] 2017-12-18 07:20
17.3.0 is marked as unstable.

**Comment by TingPing** [comment] 2017-12-18 09:13
@GloriousEggroll btw if you want to test: https://github.com/flathub/flathub/pull/189

**Comment by alexlarsson** [comment] 2017-12-18 16:39
I built 17.2.7, syncing now.

**Comment by GloriousEggroll** [comment] 2017-12-19 00:59
Updated today, added glxgears to my flatpak to test and make sure it read 17.2.7 (which it did), sadly this didnt fix the issue. The git repo with the script I made to build the league flatpak can be found here with instructions:

https://github.com/GloriousEggroll/flatpak-leagueoflegends

for whatever reason, mesa does not like being run inside flatpak. still getting an average of 30 fps. exact same wine setup natively gets me ~130-170ish

**Comment by TingPing** [comment] 2017-12-19 01:30
Different LLVM version?

**Comment by GloriousEggroll** [comment] 2017-12-19 01:31
using llvm 5 on host, not sure if that makes a difference

**Comment by alexlarsson** [comment] 2017-12-19 07:59
the stable mesa update has llvm5 too. I have no idea what is different. Maybe some new feature in libdrm?

**Comment by GloriousEggroll** [comment] 2017-12-20 03:08
Eh, don't think it's libdrm, This PPA is for 17.3 stable on ubuntu, and it uses the same libdrm version as flatpak. https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa

I'm stumped. I tried using my flatpak with my native wineprefix to see if maybe it was wine related - same thing. 30 fps on a perfectly good prefix (use it daily to play the game natively). I also tried using the runtime libs that come with PoL's wine bottle, as well as Lutris's wine runtime libs. Neither had any luck. :/

**Comment by alexlarsson** [comment] 2017-12-20 09:30
Can you try running it with --device=all ? Maybe there is some other device node it can use?

**Comment by alexlarsson** [comment] 2017-12-20 09:33
Other than that, I think you need to start talking to the upstream mesa vega people on how to diagnose this...

**Comment by GloriousEggroll** [comment] 2017-12-20 14:17
It's not just vega though, the problem persists for people with RX 480/580 cards as well. :/. I'll try to test it on another wine game later today to see if the problem persists in other games via wine.

**Comment by alexlarsson** [comment] 2017-12-20 15:06
Does it constently get exactly 30fps, or is just performance shitty in general. I mean, could there be some kind of frame-rate limit happening?

**Comment by GloriousEggroll** [comment] 2017-12-20 15:12
performance shitty in general. not being limited. tested with compositor off + vblank off +vsync off, if i drop the settings to lowest it can get to around 40ish

**Comment by alexlarsson** [comment] 2017-12-20 15:30
I have no idea how flatpak could affect things in that way, either it should work the same, or it shouldn't at all due to something it needs being sandboxed. There might be some detail different in how we build mesa (although there is nothing special with it) or some dependency, but I really fail to see how it could work, just slower...

**Comment by alexlarsson** [comment] 2017-12-20 15:39
@airlied any idea what could cause the radeon driver to be slow like this or how to debug it?

**Comment by alexlarsson** [comment] 2017-12-20 16:05
What kernel are you running

**Comment by GloriousEggroll** [comment] 2017-12-20 19:05
4.15-git. I'm rewriting my script as well to use flatpak-build for everything it needs. maybe using flatpak's build system for  the libs it needs as well as wine will help. seems it needs to be done that way anyway

**Comment by halfline** [comment] 2017-12-20 19:15
random stab in the dark guess with no evidence: maybe shm is getting used for something (*hand wave*) and the shared memory sharing doesn't work so well across the flatpak boundary.

**Comment by halfline** [comment] 2017-12-20 20:33
is the glxgears in org.freedesktop.GlxInfo on flathub also slow?

**Comment by GloriousEggroll** [comment] 2017-12-20 21:01
nope that ran at a solid 60 (with compositor on)

**Comment by GloriousEggroll** [comment] 2017-12-20 21:03
@TingPing I've updated the script per your suggestions.  I still need to see if I can get it to compile wine, will work on it more later today. marked it as a fixme in the script comments

https://github.com/GloriousEggroll/flatpak-leagueoflegends/blob/master/flatpak-make

**Comment by GloriousEggroll** [comment] 2017-12-21 01:33
also looks like mesa maybe was built without d3d9 support? gallium nine option is greyed out on fresh wine build 
![g9disabled](https://user-images.githubusercontent.com/11287837/34236336-1010a21c-e5c5-11e7-85a8-8e61807dff57.png)

**Comment by GloriousEggroll** [comment] 2017-12-21 05:57
I've also noticed --enable-nine is missing from mesa configure options. Any way we can get this added? I've got wine compiling with g9 patches on flatpak. Hopefully it can be used as a workaround for fps problems until this gets resolved

**Comment by GloriousEggroll** [comment] 2017-12-21 06:11
I also noticed OSmesa flag is not enabled. This could maybe have something to do with it?:
--enable-gallium-osmesa

"Mesa's off-screen interface is used for rendering into user-allocated memory without any sort of window system or operating system dependencies. That is, the GL_FRONT colorbuffer is actually a buffer in main memory, rather than a window on your display."

https://www.mesa3d.org/osmesa.html

**Comment by airlied** [comment] 2017-12-21 06:55
I don't think there is any reason for osmesa to be enabled, it's not used in normal operation.

**Comment by airlied** [comment] 2017-12-21 06:55
can you get LIBGL_DEBUG=verbose in there somehow? or get the glxinfo report?

**Comment by GloriousEggroll** [comment] 2017-12-21 07:19
here's glxinfo with LIBGL_DEBUG=verbose

it complains about not finding configuration file for drirc, not sure if that's minor or not:

[gloriouseggroll@shittywok ~]$ flatpak run org.RiotGames.leagueoflegends glxinfo > glxinfo_verbose.txt
libGL: Can't open configuration file /home/gloriouseggroll/.drirc: No such file or directory.
libGL: pci id for fd 8: 1002:687f, driver radeonsi
libGL: OpenDriver: trying /usr/lib/GL/default/lib/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/GL/default/lib/dri/radeonsi_dri.so
libGL: Can't open configuration file /home/gloriouseggroll/.drirc: No such file or directory.
/usr/share/libdrm/amdgpu.ids version: 1.0.0
libGL: Can't open configuration file /home/gloriouseggroll/.drirc: No such file or directory.
libGL: Using DRI3 for screen 0

glxinfo_verbose log:
http://ix.io/Dg8

will run the game and see if anything comes up in the log as well

**Comment by airlied** [comment] 2017-12-21 07:27
so it's not something obviously trivial, it looks like it can access the things it wants, 30fps seems like a wierd blank or sync problem with the X server/kernel.

**Comment by GloriousEggroll** [comment] 2017-12-21 07:36
here's the verbose game log
http://ix.io/Dg9

it's not locked at 30, just the average. if I lower all the settings it can get higher, but nothing near close to what i get natively

**Comment by GloriousEggroll** [comment] 2017-12-21 07:45
http://ix.io/Dgk

the 0 fps drop early on was switching from highest to lowest settings. As you can see the fps goes up, but not by much. The highest numbers were when nothing was causing action/moving on the screen

**Comment by GloriousEggroll** [comment] 2017-12-21 08:09
glxgears with vblank_mode=0 works fine:

[gloriouseggroll@shittywok bin]$ flatpak run org.RiotGames.leagueoflegends glxgears
libGL: Can't open configuration file /home/gloriouseggroll/.drirc: No such file or directory.
libGL: pci id for fd 8: 1002:687f, driver radeonsi
libGL: OpenDriver: trying /usr/lib/GL/default/lib/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/GL/default/lib/dri/radeonsi_dri.so
libGL: Can't open configuration file /home/gloriouseggroll/.drirc: No such file or directory.
/usr/share/libdrm/amdgpu.ids version: 1.0.0
ATTENTION: default value of option vblank_mode overridden by environment.
libGL: Can't open configuration file /home/gloriouseggroll/.drirc: No such file or directory.
libGL: Using DRI3 for screen 0
19468 frames in 5.0 seconds = 3893.445 FPS
25547 frames in 5.0 seconds = 5109.343 FPS
26236 frames in 5.0 seconds = 5247.120 FPS
27302 frames in 5.0 seconds = 5460.254 FPS
25506 frames in 5.0 seconds = 5099.209 FPS
25239 frames in 5.0 seconds = 5047.714 FPS
25713 frames in 5.0 seconds = 5142.414 FPS
26774 frames in 5.0 seconds = 5354.678 FPS
26271 frames in 5.0 seconds = 5254.142 FPS
25529 frames in 5.0 seconds = 5105.637 FPS
25930 frames in 5.0 seconds = 5185.825 FPS
26649 frames in 5.0 seconds = 5329.795 FPS
26926 frames in 5.0 seconds = 5385.095 FPS
27140 frames in 5.0 seconds = 5427.831 FPS
25000 frames in 5.0 seconds = 4999.998 FPS
23748 frames in 5.0 seconds = 4747.288 FPS
20425 frames in 5.0 seconds = 4084.907 FPS

**Comment by GloriousEggroll** [comment] 2018-01-10 20:53
Just touching base on this, can we get the --enable-gallium-osmesa build flaf enabled for mesa? I'm wanting to compile wine with gallium nine support for flatpak

**Comment by GloriousEggroll** [comment] 2018-01-10 20:55
Just touching base on this, can we get the --enable-nine configure flag added for mesa builds? Wanting to get wine with gallium nine flatpak'd

**Comment by phw** [comment] 2018-03-22 13:37
@matthiasclasen Mesa 17.3 was marked unstable, but 17.4 is out now. Would it be possible to update to that?

There is a color glitch in Civ6, and https://www.reddit.com/r/civ/comments/76zmcg/civ_vi_linux_blue_glitch_fixed/ claims this is fixed with Mesa 17.4

**Comment by TingPing** [comment] 2018-03-22 13:43
17.4 doesn't exist (they were referring to a never released git version), and 17.3.x are not unstable only x.y.0 releases are unstable. 18.0.0 is the next unstable release soon followed by a stable release.

**Comment by phw** [comment] 2018-03-22 13:46
@TingPing I see, looking at the Reddit thread again people there where actually using the git version of Mesa. But would it be possible to update to the latest stable 17.3.x then?

**Comment by GloriousEggroll** [comment] 2018-03-22 14:42
17.3 is very bug ridden, I don't think it's a good idea. 18.0 rcs have had much better success imo (ive also been testing them quite a bit). May be better off waiting. afaik 18.0 should be out near this friday. rc5 was just released and is supposedly the last rc before final

**Comment by tomkv** [comment] 2018-04-19 11:15
Mesa 17.2 is already unsupported, the final release was 17.2.7 in December.

Mesa 17.3 is on similar track, 17.3.9 released Apr 18 is anticipated to be the last release for 17.3 series.

There are already games on Steam, that require Mesa 18 for AMD cards.

By these measures, the version currently supplied is ancient and for some purposes, unusable. Graphics drivers are fast moving on Windows platforms too, with with interval between releases measured in weeks (in case of AMD, even 2-4 releases per month).

I suggest that the org.freedesktop.Platform.GL.default package should be updated more in line with upstream releases, just like org.freedesktop.Platform.GL.nvidia is.

**Comment by TingPing** [comment] 2018-06-27 16:28
Mesa was updated to 18.0.4, can anybody confirm this was fixed?

**Comment by pschichtel** [comment] 2018-06-27 16:35
I can confirm performance is now acceptable.

**Closed** 2018-06-27 16:38 UTC

**Comment by Pixelnarium** [comment] 2018-08-09 11:36
Is there any way to get a newer Mesa version in flatpak? Mesa 18.0.4 (and so not even 18.0.5) is from May and Mesa 18.1 is out since then with many performance and bugfixes.

I think this issue here can't be closed when there is no way to get newer Mesa versions. Maybe put Mesa in an extension? Or update it more regularly. 

edit:
Another question. Where is the current Mesa version defined? [This one here](https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/org.freedesktop.Platform.GL.mesa-stable.json.in) lists Mesa 17.2.7?

**Comment by pschichtel** [comment] 2018-08-09 12:36
A nightly would be great.

**Comment by Pobega** [comment] 2019-06-06 14:27
Agreed. Now that we're seeing video game tools like [Steam](https://flathub.org/apps/details/com.valvesoftware.Steam) and [Lutris](https://github.com/flathub/net.lutris.Lutris) gain adoption via Flatpak and with Flatpaks being the primary way to get/use these programs on distros such as Silverblue, EndlessOS, and ChromeOS/CrOS derivatives it would be great to have packages that track a more recent version of Mesa.

Currently Mesa 18.3.6 suffers from a lot of weird rendering issues in Unity games on my i915 hardware and it would just be nice to have more options for desktop adoption.

**Comment by TingPing** [comment] 2019-06-12 00:15
The current runtime repo is here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk
